openapi: 3.0.0
info:
  title: Matrix API
  description: API for matrix operations
  version: 1.0.0
tags:
  - name: Matrix API
    description: API for matrix operations
paths:
  /api/matrix/{id}:
    get:
      tags:
        - Matrix API
      summary: Get matrix by ID
      description: Retrieve a matrix by its ID
      operationId: getMatrix
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the matrix to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Matrix retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatrixResponse'
        '400':
          description: Invalid ID supplied
        '404':
          description: Matrix not found
        '500':
          description: Internal server error
    delete:
      tags:
        - Matrix API
      summary: Delete matrix by ID
      description: Delete a matrix by its ID
      operationId: deleteMatrix
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the matrix to delete
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Matrix deleted successfully
        '400':
          description: Invalid ID supplied
        '404':
          description: Matrix not found
        '500':
          description: Internal server error
  /api/matrix:
    post:
      tags:
        - Matrix API
      summary: Save matrix
      description: Save a new matrix
      operationId: saveMatrix
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatrixRequest'
      responses:
        '200':
          description: Matrix saved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatrixResponse'
        '400':
          description: Invalid matrix data supplied
        '500':
          description: Internal server error
  /api/matrix/add/{id1}/{id2}:
    get:
      tags:
        - Matrix API
      summary: Add matrices by IDs
      description: Adds two matrices by their IDs
      operationId: addMatricesByIds
      parameters:
        - name: id1
          in: path
          required: true
          description: ID of the first matrix
          schema:
            type: integer
            format: int64
        - name: id2
          in: path
          required: true
          description: ID of the second matrix
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Matrices added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatrixResponse'
        '400':
          description: Invalid IDs supplied
        '404':
          description: Matrix not found
        '500':
          description: Internal server error
  /api/matrix/add:
    post:
      tags:
        - Matrix API
      summary: Add matrices
      description: Adds two matrices provided in the request body
      operationId: addMatrices
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatrixAdditionRequest'
      responses:
        '200':
          description: Matrices added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MatrixResponse'
        '400':
          description: Invalid matrix data supplied
        '500':
          description: Internal server error
components:
  schemas:
    MatrixRequest:
      type: object
      properties:
        matrix:
          type: array
          items:
            type: array
            items:
              type: integer
    MatrixResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        message:
          type: string
        matrix:
          type: array
          items:
            type: array
            items:
              type: integer
    MatrixAdditionRequest:
      type: object
      properties:
        matrix1:
          $ref: '#/components/schemas/MatrixRequest'
        matrix2:
          $ref: '#/components/schemas/MatrixRequest'